export default {
  SIGNIN_S: "SIGNIN_S",
  SIGNIN_F: "SIGNIN_F",
  SIGNIN_R: "SIGNIN_R",

  GET_USERS_S: "GET_USERS_S",
  GET_USERS_F: "GET_USERS_F",
  GET_USERS_R: "GET_USERS_R",

  APPROVE_S: "APPROVE_S",
  APPROVE_F: "APPROVE_F",
  APPROVE_R: "APPROVE_R",

  REVOKE_S: "REVOKE_S",
  REVOKE_F: "REVOKE_F",
  REVOKE_R: "REVOKE_R"
};
