export default {
  SIGNIN_SUCCESSFUL: "SIGNIN_SUCCESSFUL",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNIN_IN_PROGRESS: "SIGNIN_IN_PROGRESS",

  FETCH_USERS_SUCCESSFUL: "FETCH_USERS_SUCCESSFUL",
  FETCH_USERS_FAILED: "FETCH_USERS_FAILED",
  FETCH_USERS_IN_PROGRESS: "FETCH_USERS_IN_PROGRESS",

  APPROVE_SUCCESSFUL: "APPROVE_SUCCESSFUL",
  APPROVE_FAILED: "APPROVE_FAILED",
  APPROVE_IN_PROGRESS: "APPROVE_IN_PROGRESS",

  REVOKE_SUCCESSFUL: "REVOKE_SUCCESSFUL",
  REVOKE_FAILED: "REVOKE_FAILED",
  REVOKE_IN_PROGRESS: "REVOKE_IN_PROGRESS"
};
