export default {
  SIGNOUT: "SIGNOUT",
  CLEAR: "CLEAR",
  SIGNIN_SUCCESSFUL: "SIGNIN_SUCCESSFUL",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNIN_IN_PROGRESS: "SIGNIN_IN_PROGRESS",

  TOKEN_VERIFICATION_SUCCESSFUL: "TOKEN_VERIFICATION_SUCCESSFUL",
  TOKEN_VERIFICATION_FAILED: "TOKEN_VERIFICATION_FAILED",
  TOKEN_VERIFICATION_IN_PROGRESS: "TOKEN_VERIFICATION_IN_PROGRESS",

  SIGNUP_SUCCESSFUL: "SIGNUP_SUCCESSFUL",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_IN_PROGRESS: "SIGNUP_IN_PROGRESS",

  UPDATE_PASSWORD_IN_PROGRESS:"UPDATE_PASSWORD_IN_PROGRESS",
  UPDATE_PASSWORD_SUCCESSFUL:"UPDATE_PASSWORD_SUCCESSFUL",
  UPDATE_PASSWORD_FAILED:"UPDATE_PASSWORD_FAILED",
  
  INIT_ACCOUNT_RECOVERY_SUCCESSFUL: "INIT_ACCOUNT_RECOVERY_SUCCESSFUL",
  INIT_ACCOUNT_RECOVERY_FAILED: "INIT_ACCOUNT_RECOVERY_FAILED",
  INIT_ACCOUNT_RECOVERY_IN_PROGRESS: "INIT_ACCOUNT_RECOVERY_IN_PROGRESS",

  SEND_RECOVERY_MAIL_SUCCESSFUL: "SEND_RECOVERY_MAIL_SUCCESSFUL",
  SEND_RECOVERY_MAIL_FAILED: "SEND_RECOVERY_MAIL_FAILED",
  SEND_RECOVERY_MAIL_IN_PROGRESS: "SEND_RECOVERY_MAIL_IN_PROGRESS",

  CHANGE_USER_DETAILS_IN_PROGRESS: "CHANGE_USER_DETAILS_IN_PROGRESS",
  CHANGE_USER_DETAILS_SUCCESSFUL: "CHANGE_USER_DETAILS_SUCCESSFUL",
  CHANGE_USER_DETAILS_FAILED: "CHANGE_USER_DETAILS_FAILED"
};
