export default {
    GET_INIT_NOTIFICATIONS_FAILED: "GET_INIT_NOTIFICATIONS_FAILED",
    GET_INIT_NOTIFICATIONS_SUCCESSFUL: 'GET_INIT_NOTIFICATIONS_SUCCESSFUL',
    GET_INIT_NOTIFICATIONS_REQUEST: 'GET_INIT_NOTIFICATIONS_REQUEST',

    MARK_NOTIFICATIONS_FAILED: "MARK_NOTIFICATIONS_FAILED",
    MARK_NOTIFICATIONS_SUCCESSFUL: 'MARK_NOTIFICATIONS_SUCCESSFUL',
    MARK_NOTIFICATIONS_REQUEST: 'MARK_NOTIFICATIONS_REQUEST',
    
    UPDATE_NOTIFICATIONS_SUCCESSFUL: 'UPDATE_NOTIFICATIONS_SUCCESSFUL',
    SAVE_SOCKET_DATA:"SAVE_SOCKET_DATA"
}