export default {
    GET_INIT_NOTIFICATIONS_F: "GET_INIT_NOTIFICATIONS_F",
    GET_INIT_NOTIFICATIONS_S: 'GET_INIT_NOTIFICATIONS_S',
    GET_INIT_NOTIFICATIONS_R: 'GET_INIT_NOTIFICATIONS_R',

    MARK_NOTIFICATIONS_F: "MARK_NOTIFICATIONS_F",
    MARK_NOTIFICATIONS_S: 'MARK_NOTIFICATIONS_S',
    MARK_NOTIFICATIONS_R: 'MARK_NOTIFICATIONS_R',
    
    UPDATE_NOTIFICATIONS_S: 'UPDATE_NOTIFICATIONS_S',
    SAVE_SOCKET_DATA:"SAVE_SOCKET_DATA"
}