export default {
    GET_INIT_NOTIFICATIONS_FAILED: "GET_INIT_NOTIFICATIONS_FAILED",
    GET_INIT_NOTIFICATIONS_SUCCESSFUL: 'GET_INIT_NOTIFICATIONS_SUCCESSFUL',
    GET_INIT_NOTIFICATIONS_REQUEST: 'GET_INIT_NOTIFICATIONS_REQUEST'
}