export default {
  SIGNOUT: "SIGNOUT",
  CLEAR: "CLEAR",
  SIGNIN_S: "SIGNIN_S",
  SIGNIN_F: "SIGNIN_F",
  SIGNIN_R: "SIGNIN_R",
  SET_INTERESTS: "SET_INTERESTS",

  TOKEN_VERIFICATION_S: "TOKEN_VERIFICATION_S",
  TOKEN_VERIFICATION_F: "TOKEN_VERIFICATION_F",
  TOKEN_VERIFICATION_R: "TOKEN_VERIFICATION_R",

  SIGNUP_S: "SIGNUP_S",
  SIGNUP_F: "SIGNUP_F",
  SIGNUP_R: "SIGNUP_R",

  UPDATE_PASSWORD_R:"UPDATE_PASSWORD_R",
  UPDATE_PASSWORD_S:"UPDATE_PASSWORD_S",
  UPDATE_PASSWORD_F:"UPDATE_PASSWORD_F",
  
  INIT_ACCOUNT_RECOVERY_S: "INIT_ACCOUNT_RECOVERY_S",
  INIT_ACCOUNT_RECOVERY_F: "INIT_ACCOUNT_RECOVERY_F",
  INIT_ACCOUNT_RECOVERY_R: "INIT_ACCOUNT_RECOVERY_R",

  SEND_RECOVERY_MAIL_S: "SEND_RECOVERY_MAIL_S",
  SEND_RECOVERY_MAIL_F: "SEND_RECOVERY_MAIL_F",
  SEND_RECOVERY_MAIL_R: "SEND_RECOVERY_MAIL_R",

  RESEND_VERIFICATION_R: "RESEND_VERIFICATION_R",
  RESEND_VERIFICATION_S: "RESEND_VERIFICATION_S",
  RESEND_VERIFICATION_F: "RESEND_VERIFICATION_F",

  EMAIL_VERIFICATION_R: "EMAIL_VERIFICATION_R",
  EMAIL_VERIFICATION_S: "EMAIL_VERIFICATION_S",
  EMAIL_VERIFICATION_F: "EMAIL_VERIFICATION_F",

  CHANGE_USER_DETAILS_R: "CHANGE_USER_DETAILS_R",
  CHANGE_USER_DETAILS_S: "CHANGE_USER_DETAILS_S",
  CHANGE_USER_DETAILS_F: "CHANGE_USER_DETAILS_F"
};
