export default {
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_IN_PROGRESS: "LOGIN_IN_PROGRESS",

  TOKEN_VERIFICATION_SUCCESSFUL: "TOKEN_VERIFICATION_SUCCESSFUL",
  TOKEN_VERIFICATION_FAILED: "TOKEN_VERIFICATION_FAILED",
  TOKEN_VERIFICATION_IN_PROGRESS: "TOKEN_VERIFICATION_IN_PROGRESS",

  SIGNUP_SUCCESSFUL: "SIGNUP_SUCCESSFUL",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_IN_PROGRESS: "SIGNUP_IN_PROGRESS",

  INIT_ACCOUNT_RECOVERY_SUCCESSFUL: "INIT_ACCOUNT_RECOVERY_SUCCESSFUL",
  INIT_ACCOUNT_RECOVERY_FAILED: "INIT_ACCOUNT_RECOVERY_FAILED",
  INIT_ACCOUNT_RECOVERY_IN_PROGRESS: "INIT_ACCOUNT_RECOVERY_IN_PROGRESS",

  SEND_RECOVERY_MAIL_SUCCESSFUL: "SEND_RECOVERY_MAIL_SUCCESSFUL",
  SEND_RECOVERY_MAIL_FAILED: "SEND_RECOVERY_MAIL_FAILED",
  SEND_RECOVERY_MAIL_IN_PROGRESS: "SEND_RECOVERY_MAIL_IN_PROGRESS"
};
