export default {
  FETCHING_PROJECTS_IN_PROGRESS: "FETCHING_PROJECTS_IN_PROGRESS",
  FETCHING_PROJECTS_SUCCESSFUL: "FETCHING_PROJECTS_SUCCESSFUL",
  FETCHING_PROJECTS_FAILED: "FETCHING_PROJECTS_FAILED",

  FETCHING_PROJECT_IN_PROGRESS: "FETCHING_PROJECT_IN_PROGRESS",
  FETCHING_PROJECT_SUCCESSFUL: "FETCHING_PROJECT_SUCCESSFUL",
  FETCHING_PROJECT_FAILED: "FETCHING_PROJECT_FAILED",

  ADD_PROJECT_IN_PROGRESS: "ADD_PROJECT_IN_PROGRESS",
  ADD_PROJECT_SUCCESSFUL: "ADD_PROJECT_SUCCESSFUL",
  ADD_PROJECT_FAILED: "ADD_PROJECT_FAILED",

  ADD_TASK_IN_PROGRESS: "ADD_TASK_IN_PROGRESS",
  ADD_TASK_SUCCESSFUL: "ADD_TASK_SUCCESSFUL",
  ADD_TASK_FAILED: "ADD_TASK_FAILED",

  CLOSE_MODAL_FORM: "CLOSE_MODAL_FORM",
  SHOW_MODAL_FORM: "SHOW_MODAL_FORM"
};
