export default {
  FETCHING_PROJECTS_IN_PROGRESS: "FETCHING_PROJECTS_IN_PROGRESS",
  FETCHING_PROJECTS_SUCCESSFUL: "FETCHING_PROJECTS_SUCCESSFUL",
  FETCHING_PROJECTS_FAILED: "FETCHING_PROJECTS_FAILED",
  CLOSE_MODAL_FORM: "CLOSE_MODAL_FORM",
  SHOW_MODAL_FORM: "SHOW_MODAL_FORM"
};
