export const SPECIFY_KPI_R = 'SPECIFY_KPI_R';
export const SPECIFY_KPI_S = 'SPECIFY_KPI_S';
export const SPECIFY_KPI_F = 'SPECIFY_KPI_F';

export const RETRIEVE_KPIS_R = 'RETRIEVE_KPIS_R';
export const RETRIEVE_KPIS_S = 'RETRIEVE_KPIS_S';
export const RETRIEVE_KPIS_F = 'RETRIEVE_KPIS_F';

export const SUBMIT_EVIDENCE_R = 'SUBMIT_EVIDENCE_R';
export const SUBMIT_EVIDENCE_S = 'SUBMIT_EVIDENCE_S';
export const SUBMIT_EVIDENCE_F = 'SUBMIT_EVIDENCE_F';
