export const SPECIFY_KPI_R = 'SPECIFY_KPI_R';
export const SPECIFY_KPI_S = 'SPECIFY_KPI_S';
export const SPECIFY_KPI_F = 'SPECIFY_KPI_F';

export const RETRIEVE_KPIS_R = 'RETRIEVE_KPIS_R';
export const RETRIEVE_KPIS_S = 'RETRIEVE_KPIS_S';
export const RETRIEVE_KPIS_F = 'RETRIEVE_KPIS_F';

export const SUBMIT_EVIDENCE_R = 'SUBMIT_EVIDENCE_R';
export const SUBMIT_EVIDENCE_S = 'SUBMIT_EVIDENCE_S';
export const SUBMIT_EVIDENCE_F = 'SUBMIT_EVIDENCE_F';

export const UPDATE_OBSERVATION_BUDGET = 'UPDATE_OBSERVATION_BUDGET';

export const RETRIEVE_SUBMISSION_R = 'RETRIEVE_SUBMISSION_R';
export const RETRIEVE_SUBMISSION_S = 'RETRIEVE_SUBMISSION_S';
export const RETRIEVE_SUBMISSION_F = 'RETRIEVE_SUBMISSION_F';

export const SELECT_TASK_SUBMISSIONS = 'SELECT_TASK_SUBMISSIONS';