export default {
  FETCHING_HOMEPAGE_PROJECTS_IN_PROGRESS:
    "FETCHING_HOMEPAGE_PROJECTS_IN_PROGRESS",
  FETCHING_HOMEPAGE_PROJECTS_SUCCESSFUL:
    "FETCHING_HOMEPAGE_PROJECTS_SUCCESSFUL",
  FETCHING_HOMEPAGE_PROJECTS_FAILED: "FETCHING_HOMEPAGE_PROJECTS_FAILED",

  FETCHING_HOMEPAGE_PROJECT_IN_PROGRESS:
    "FETCHING_HOMEPAGE_PROJECT_IN_PROGRESS",
  FETCHING_HOMEPAGE_PROJECT_SUCCESSFUL: "FETCHING_HOMEPAGE_PROJECT_SUCCESSFUL",
  FETCHING_HOMEPAGE_PROJECT_FAILED: "FETCHING_HOMEPAGE_PROJECT_FAILED"
};
