export default {
  GET_HOMEPAGE_PROJS_R:
    "GET_HOMEPAGE_PROJS_R",
  GET_HOMEPAGE_PROJS_S:
    "GET_HOMEPAGE_PROJS_S",
  GET_HOMEPAGE_PROJS_F: "GET_HOMEPAGE_PROJS_F",

  GET_HOMEPAGE_PROJ_R:
    "GET_HOMEPAGE_PROJ_R",
  GET_HOMEPAGE_PROJ_S: "GET_HOMEPAGE_PROJ_S",
  GET_HOMEPAGE_PROJ_F: "GET_HOMEPAGE_PROJ_F",

  GET_LOCATIONS_S: "GET_LOCATIONS_S",

  SHOW_MAP: "SHOW_MAP",
  TOGGLE_FULLSCREEN: "TOGGLE_FULLSCREEN",
  IGNORE_PROJ_ID: "IGNORE_PROJ_ID",
  GET_CITIZEN_INFO_S: "GET_CITIZEN_INFO_S",
  GET_CITIZEN_INFO_R: "GET_CITIZEN_INFO_R",
  GET_CITIZEN_INFO_F: "GET_CITIZEN_INFO_F"
};
