export default {
    CREATE_TASK: "CREATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    REMOVE_TASK: "REMOVE_TASK",

    SET_PROPOSAL_NAME: 'SET_PROPOSAL_NAME',
    
    CREATE_MILESTONE:"CREATE_MILESTONE",
    SET_MILESTONE_NAME: 'SET_MILESTONE_NAME',

    DELETE_MILESTONE:"DELETE_MILESTONE",

    SUBMIT_PROPOSAL_R:"SUBMIT_PROPOSAL_R",
    SUBMIT_PROPOSAL_F:"SUBMIT_PROPOSAL_F",
    SUBMIT_PROPOSAL_S:"SUBMIT_PROPOSAL_S",
    
    GET_PROPOSALS_R:"GET_PROPOSALS_R",
    GET_PROPOSALS_F:"GET_PROPOSALS_F",
    GET_PROPOSALS_S:"GET_PROPOSALS_S",
    
    GET_ONE_PROPOSAL_R:"GET_ONE_PROPOSAL_R",
    GET_ONE_PROPOSAL_F:"GET_ONE_PROPOSAL_F",
    GET_ONE_PROPOSAL_S:"GET_ONE_PROPOSAL_S",
    
    SWITCH_VIEW: 'SWITCH_VIEW',
    CLEAR_PROPOSAL: 'CLEAR_PROPOSAL',

    CREATE_COMMENT: "CREATE_COMMENT",
    ATTACH_CONTRACTOR: "ATTACH_CONTRACTOR",
    VIEW_TASK: "VIEW_TASK",
}
