export const CLEAR = "CLEAR";
export const SHOW_INTERESTS_MODAL = "SHOW_INTERESTS_MODAL";
export const SHOW_ADD_PROJECT_MODAL = "SHOW_ADD_PROJECT_MODAL";
export const CLOSE_MODAL_FORM = "CLOSE_MODAL_FORM";
export const SHOW_MODAL_FORM = "SHOW_MODAL_FORM";
export const SHOW_IMAGE_IN_MODAL_FORM = "SHOW_IMAGE_IN_MODAL_FORM";
export const SHOW_TASK_MODAL = "SHOW_TASK_MODAL";
export const SHOW_DELETE_MODAL_FORM = "SHOW_DELETE_MODAL_FORM";
export const SHOW_STAKEHOLDER_MODAL = "SHOW_STAKEHOLDER_MODAL";
export const SHOW_ADD_STAKEHOLDER_MODAL = "SHOW_ADD_STAKEHOLDER_MODAL";
export const SHOW_ADD_TASK_MODAL = "SHOW_ADD_TASK_MODAL";
export const SHOW_EDIT_TASK_MODAL = "SHOW_EDIT_TASK_MODAL";
export const SHOW_MODIFY_TASK_MODAL = 'SHOW_MODIFY_TASK_MODAL';
export const SHOW_ADD_TRANSACTION_MODAL = "SHOW_ADD_TRANSACTION_MODAL";
export const SHOW_ADD_DOCUMENT_MODAL = "SHOW_ADD_DOCUMENT_MODAL";
export const SHOW_VIEW_TASK_MODAL = 'SHOW_VIEW_TASK_MODAL';
  