export default {
  FETCH_ORGANIZATION_IN_PROGESS: "FETCH_ORGANIZATION_IN_PROGESS",
  FETCH_ORGANIZATIONS_SUCCESSFUL: "FETCH_ORGANIZATIONS_SUCCESSFUL",
  FETCH_ORGANIZATIONS_FAILED: "FETCH_ORGANIZATIONS_FAILED"
};
