export default {
    CREATE_TASK: "CREATE_TASK",
    CREATE_MILESTONE:"CREATE_MILESTONE",
    SET_MILESTONE_NAME: 'SET_MILESTONE_NAME',
    REMOVE_MILESTONE:"REMOVE_MILESTONE",
    REMOVE_TASK: "REMOVE_TASK",
    SUBMIT_PROPOSAL_R:"SUBMIT_PROPOSAL_R",
    SUBMIT_PROPOSAL_F:"SUBMIT_PROPOSAL_F",
    SUBMIT_PROPOSAL_S:"SUBMIT_PROPOSAL_S",
    SWITCH_VIEW: 'SWITCH_VIEW',

    TASK_TO_MODIFY: 'TASK_TO_MODIFY'
}
