export const FETCH_MY_WALLET_R = "FETCH_MY_WALLET_R";
export const FETCH_MY_WALLET_S = "FETCH_MY_WALLET_S";
export const FETCH_MY_WALLET_F = "FETCH_MY_WALLET_F";

export const FETCH_MY_TRANSACTIONS_R = "FETCH_MY_TRANSACTIONS_R";
export const FETCH_MY_TRANSACTIONS_S = "FETCH_MY_TRANSACTIONS_S";
export const FETCH_MY_TRANSACTIONS_F = "FETCH_MY_TRANSACTIONS_F";


export const CLEAR_WALLET = 'CLEAR_WALLET';