export default {
    JOIN_PROJ_AS_CONTRACTOR_S:'JOIN_PROJ_AS_CONTRACTOR_S',
    JOIN_PROJ_AS_CONTRACTOR_F: 'JOIN_PROJ_AS_CONTRACTOR_F',
    REJECT_PROJ_AS_CONTRACTOR_S:'REJECT_PROJ_AS_CONTRACTOR_S',
    REJECT_PROJ_AS_CONTRACTOR_F: 'REJECT_PROJ_AS_CONTRACTOR_F',
    FETCH_P_P_R:'FETCH_P_P_R',
    FETCH_P_P_S:'FETCH_P_P_S',
    FETCH_P_P_F:'FETCH_P_P_F'
}