export default {
  GET_PROJS_AS_CONTRACTOR_R: "GET_PROJS_AS_CONTRACTOR_R",
  GET_PROJS_AS_CONTRACTOR_S: "GET_PROJS_AS_CONTRACTOR_S",
  GET_PROJS_AS_CONTRACTOR_F: "GET_PROJS_AS_CONTRACTOR_F",

  DELETE_PROJ_S: "DELETE_PROJ_S",
  DELETE_PROJ_F: "DELETE_PROJ_F",
  DELETE_PROJ_R: "DELETE_PROJ_R",

  GET_PROJ_R: "GET_PROJ_R",
  GET_PROJ_S: "GET_PROJ_S",
  GET_PROJ_F: "GET_PROJ_F",

  GET_P_STAKEHOLDERS_R: "GET_P_STAKEHOLDERS_R",
  GET_P_STAKEHOLDERS_S: "GET_P_STAKEHOLDERS_S",
  GET_P_STAKEHOLDERS_F: "GET_P_STAKEHOLDERS_F",

  ADD_PROJ_R: "ADD_PROJ_R",
  ADD_PROJ_S: "ADD_PROJ_S",
  ADD_PROJ_F: "ADD_PROJ_F",

  ADD_STAKEHOLDER_R: "ADD_STAKEHOLDER_R",
  ADD_STAKEHOLDER_S: "ADD_STAKEHOLDER_S",
  ADD_STAKEHOLDER_F: "ADD_STAKEHOLDER_F",

  ADD_TASK_R: "ADD_TASK_R",
  ADD_TASK_S: "ADD_TASK_S",
  ADD_TASK_F: "ADD_TASK_F",

  ADD_DOCUMENT_R: "ADD_DOCUMENT_R",
  ADD_DOCUMENT_S: "ADD_DOCUMENT_S",
  ADD_DOCUMENT_F: "ADD_DOCUMENT_F",

  ADD_TRANSACTION_R: "ADD_TRANSACTION_R",
  ADD_TRANSACTION_S: "ADD_TRANSACTION_S",
  ADD_TRANSACTION_F: "ADD_TRANSACTION_F",

  GET_TASKS_R: "GET_TASKS_R",
  GET_TASKS_S: "GET_TASKS_S",
  GET_TASKS_F: "GET_TASKS_F",

  GET_TASK_R: "GET_TASK_R",
  GET_TASK_S: "GET_TASK_S",
  GET_TASK_F: "GET_TASK_F",

  CLOSE_MODAL_FORM: "CLOSE_MODAL_FORM",

  SHOW_MODAL_FORM: "SHOW_MODAL_FORM",
  SHOW_IMAGE_IN_MODAL_FORM: "SHOW_IMAGE_IN_MODAL_FORM",
  SHOW_TASK_MODAL: "SHOW_TASK_MODAL",
  SHOW_DELETE_MODAL_FORM: "SHOW_DELETE_MODAL_FORM",
  SHOW_STAKEHOLDER_MODAL: "SHOW_STAKEHOLDER_MODAL",

  SHOW_ADD_STAKEHOLDER_MODAL: "SHOW_ADD_STAKEHOLDER_MODAL",
  SHOW_ADD_TASK_MODAL: "SHOW_ADD_TASK_MODAL",
  SHOW_ADD_TRANSACTION_MODAL: "SHOW_ADD_TRANSACTION_MODAL",
  SHOW_ADD_DOCUMENT_MODAL: "SHOW_ADD_DOCUMENT_MODAL",

  WATCH_VIDEO: "WATCH_VIDEO",
  CLEAR_VIDEO: "CLEAR_VIDEO",
  CLEAR_ADD: "CLEAR_ADD",

  SELECT_FUNDERS: "SELECT_FUNDERS"
};
