export default {
    JOIN_PROJ_AS_CONTRACTOR__S:'JOIN_PROJ_AS_CONTRACTOR__S',
    JOIN_PROJ_AS_CONTRACTOR__F: 'JOIN_PROJ_AS_CONTRACTOR__F',
    REJECT_PROJ_AS_CONTRACTOR__S:'REJECT_PROJ_AS_CONTRACTOR__S',
    REJECT_PROJ_AS_CONTRACTOR__F: 'REJECT_PROJ_AS_CONTRACTOR__F',
}