// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './chart.css';

function render() {
    return <div className="chart-chart-3">
        <div className="chart-0">
            <div className="chart-fundingchart-3">
                <div className="chart-0-0-0">
                    <div className="chart-0-0-0-0">
                        <div className="chart-0-0-0-0-0">
                            <div className="chart-text_2">
                                {"Used funding / Projects fullfilment"}
                            </div>
                        </div>
                    </div>
                    <div className="chart-rectangle_4">
                        <div className="chart-0-0-0-1-0">
                            <div className="chart-0-0-0-1-0-0">
                                <div className="chart-0-0-0-1-0-0-0">
                                    <div className="chart-oval-7" /> 
                                </div>
                            </div>
                            <div className="chart-text_3">Funding</div>
                        </div>
                    </div>
                    <div className="chart-rectangle_5">
                        <div className="chart-0-0-0-2-0">
                            <div className="chart-0-0-0-2-0-0">
                                <div className="chart-0-0-0-2-0-0-0">
                                    <div className="chart-oval-5" /> 
                                </div>
                            </div>
                            <div className="chart-text_4">Fulfillment</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}