// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './convlist.css';

function render() {
    return <div className="convlist">
        { (this.props.state === "default") ?
            <div className="convlist-default-0">
                <div className="convlist-0-0-0">
                    <div className="convlist-rectangle_20">
                        <div className="convlist-0-0-0-0-0">
                            <div className="convlist-rectangle_3">
                                <div className="convlist-0-0-0-0-0-0-0">
                                    <div className="convlist-text_1">CONVERSATIONS</div>
                                </div>
                            </div>
                        </div>
                        <div className="convlist-0-0-0-0-1">
                            <div className="convlist-rectangle_2">
                                { this.props.list.map((item, i) => {
                                    return <div key={i} className="convlist-rectangle-5">
                                        <div className="convlist-0-0-0-0-1-0-0-0-0">
                                            <img src={item.profilePicture} className="convlist-image-8" /> 
                                            <div className="convlist-0-0-0-0-1-0-0-0-0-1">
                                                <div className="convlist-0-0-0-0-1-0-0-0-0-1-0">
                                                    <div className="convlist-text_10">{ item.firstName }</div>
                                                </div>
                                                <div className="convlist-0-0-0-0-1-0-0-0-0-1-1">
                                                    <div className="convlist-text_10-5">{ item.lastName }</div>
                                                </div>
                                            </div>
                                            <div className="convlist-0-0-0-0-1-0-0-0-0-2">
                                                <div className="convlist-0-0-0-0-1-0-0-0-0-2-0">
                                                    <div className="convlist-text_11">{ item.text }</div>
                                                </div>
                                            </div>
                                            <div className="convlist-0-0-0-0-1-0-0-0-0-3">
                                                <div className="convlist-0-0-0-0-1-0-0-0-0-3-0">
                                                    <div className="convlist-text_12">{ item.dateSince }</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="convlist-0-0-1" /> 
            </div>
        : null}
        { (this.props.state === "empty") ?
            <div className="convlist-empty-9">
                <div className="convlist-1-0-0">
                    <div className="convlist-rectangle_1">
                        <div className="convlist-1-0-0-0-0">
                            <div className="convlist-rectangle_3-6">
                                <div className="convlist-1-0-0-0-0-0-0">
                                    <div className="convlist-text_13">CONVERSATIONS</div>
                                </div>
                            </div>
                        </div>
                        <div className="convlist-1-0-0-0-1">
                            <div className="convlist-1-0-0-0-1-0" /> 
                            <div className="convlist-text_14">
                                {"No conversations started."}
                            </div>
                            <div className="convlist-1-0-0-0-1-2" /> 
                        </div>
                        <div className="convlist-1-0-0-0-2" /> 
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}