// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './dashboardblock.css';

function render() {
    return <div className="dashboardblock-dashboardblock-4">
        <div className="dashboardblock-0">
            <div className="dashboardblock-card-5">
                <div className="dashboardblock-0-0-0">
                    <div className="dashboardblock-card-3" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}