// Generated by https://pagedraw.io/pages/8218
import Pie from '../components/piechart'
import SmsList from '../components/sms' 
import Disputeslist from './disputeslist';
import Convlist from './convlist';
import Paymentlist from './paymentlist';
import Taskupdateslist from './taskupdateslist';
import React from 'react';
import './dashboard.css';

function render() {
    return <div className="dashboard-dashboard-8" style={{"background": ('#fafafa')}}>
        <div className="dashboard-0">
            <div className="dashboard-0-0">
                <div className="dashboard-0-0-0">
                    <div className="dashboard-disputeslist_instance-8">
                        <Disputeslist state={(this.props.disputes ? 'default' : 'empty')} list={this.props.disputes} /> 
                    </div>
                </div>
            </div>
            <div className="dashboard-convlist_instance-6">
                <Convlist list={this.props.conversations} state={(this.props.conversations ? 'default' : 'empty')} /> 
            </div>
        </div>
        <div className="dashboard-1">
            <div className="dashboard-paymentlist_instance-6">
                <Paymentlist list={this.props.payments} state={(this.props.payments ? 'default' : 'empty')} /> 
            </div>
            <div className="dashboard-taskupdateslist_instance-9">
                <Taskupdateslist state={(this.props.taskUpdates ? 'default' : 'empty')} list={[]} /> 
            </div>
        </div>
        <div className="dashboard-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}