// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './disputeslist.css';

function render() {
    return <div className="disputeslist">
        { (this.props.state === "default") ?
            <div className="disputeslist-default-3">
                <div className="disputeslist-0-0-0">
                    <div className="disputeslist-rectangle_1">
                        <div className="disputeslist-0-0-0-0-0">
                            <div className="disputeslist-title-4">
                                <div className="disputeslist-0-0-0-0-0-0-0">
                                    <div className="disputeslist-text-1">DISPUTES</div>
                                </div>
                            </div>
                        </div>
                        <div className="disputeslist-0-0-0-0-1">
                            <div className="disputeslist-disputescontent-4">
                                <div className="disputeslist-0-0-0-0-1-0-0">
                                    <div className="disputeslist-0-0-0-0-1-0-0-0">
                                        { this.props.list.map((item, i) => {
                                            return <div key={i} className="disputeslist-disputeitem-3">
                                                <div className="disputeslist-0-0-0-0-1-0-0-0-0-0-0">
                                                    <div className="disputeslist-0-0-0-0-1-0-0-0-0-0-0-0">
                                                        <div className="disputeslist-0-0-0-0-1-0-0-0-0-0-0-0-0">
                                                            <div className="disputeslist-oval_2" style={{"background": (item.status || 'rgb(203, 124, 60)')}} /> 
                                                        </div>
                                                    </div>
                                                    <div className="disputeslist-text_8">
                                                        { item.projectName }
                                                    </div>
                                                    <div className="disputeslist-0-0-0-0-1-0-0-0-0-0-0-2">
                                                        <div className="disputeslist-0-0-0-0-1-0-0-0-0-0-0-2-0">
                                                            <div className="disputeslist-text_9">
                                                                { item.dateSince }
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>;
                                        }) }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="disputeslist-0-0-0-0-2" /> 
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state === "empty") ?
            <div className="disputeslist-empty-9">
                <div className="disputeslist-1-0-0">
                    <div className="disputeslist-rectangle_18">
                        <div className="disputeslist-1-0-0-0-0">
                            <div className="disputeslist-title-2">
                                <div className="disputeslist-1-0-0-0-0-0-0">
                                    <div className="disputeslist-text-4">DISPUTES</div>
                                </div>
                            </div>
                        </div>
                        <div className="disputeslist-1-0-0-0-1">
                            <div className="disputeslist-text_1">
                                {"No claims have been disputed."}
                            </div>
                        </div>
                    </div>
                </div>
                <div className="disputeslist-1-0-1" /> 
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}