// Generated by https://pagedraw.io/pages/8218
import Mapinfo from './mapinfo';
import React from 'react';
import './map.css';

function render() {
    return <div className="map-map-3">
        <div className="map-0">
            <div className="map-rectangle_19">
                <div className="map-0-0-0">
                    <div className="map-rectangle_1" /> 
                    <div className="map-0-0-0-1" /> 
                    <div className="map-mapinfo_instance-6">
                        <Mapinfo projectName={(this.props.selected && this.props.selected.projectName)} milestonesCount={(this.props.selected && this.props.selected.milestonesCount)} tasksCount={(this.props.selected && this.props.selected.tasksCount)} progress={(this.props.selected && this.props.selected.progress)} currentMilestone={(this.props.selected && this.props.selected.currentMilestone)} /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="map-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}