// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './mapinfo.css';

function render() {
    return <div className="mapinfo">
        { ((this.props.projectName ? 'default' : 'empty') === "empty") ?
            <div className="mapinfo-empty-4">
                <div className="mapinfo-0-0-0">
                    <div className="mapinfo-rectangle_1">
                        <div className="mapinfo-0-0-0-0-0">
                            <div className="mapinfo-0-0-0-0-0-0" /> 
                            <div className="mapinfo-text_2">
                                Hover on a project location  to show details
                            </div>
                            <div className="mapinfo-0-0-0-0-0-2" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}