// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './paymentslist.css';

function render() {
    return <div className="paymentslist-paymentslist-4">
        <div className="paymentslist-0">
            <div className="paymentslist-paymentlistheader-6">
                <div className="paymentslist-0-0-0">
                    <div className="paymentslist-text2">PAYMENTS</div>
                </div>
            </div>
        </div>
        <div className="paymentslist-1">
            <div className="paymentslist-paymentlistcontent-7">
                <div className="paymentslist-1-0-0">
                    <div className="paymentslist-paylistheaders-9">
                        <div className="paymentslist-1-0-0-0-0">
                            <div className="paymentslist-paylistheader1">Project</div>
                            <div className="paymentslist-paylistheader2">Details</div>
                        </div>
                    </div>
                </div>
                <div className="paymentslist-1-0-1">
                    <div className="paymentslist-1-0-1-0">
                        { this.props.list.map((item, i) => {
                            return <div key={i} className="paymentslist-paymentitem-6">
                                <div className="paymentslist-1-0-1-0-0-0-0">
                                    <div className="paymentslist-1-0-1-0-0-0-0-0">
                                        <div className="paymentslist-1-0-1-0-0-0-0-0-0">
                                            <img src={item.profilePicture} className="paymentslist-paymentprofile-5" /> 
                                        </div>
                                    </div>
                                    <div className="paymentslist-1-0-1-0-0-0-0-1">
                                        <div className="paymentslist-1-0-1-0-0-0-0-1-0">
                                            <div className="paymentslist-text25">
                                                { item.firstName }
                                            </div>
                                        </div>
                                        <div className="paymentslist-1-0-1-0-0-0-0-1-1">
                                            <div className="paymentslist-text26">
                                                { item.lastName }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="paymentslist-1-0-1-0-0-0-0-2">
                                        <div className="paymentslist-1-0-1-0-0-0-0-2-0">
                                            <div className="paymentslist-text21">
                                                { item.projectName }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="paymentslist-1-0-1-0-0-0-0-3">
                                        <div className="paymentslist-1-0-1-0-0-0-0-3-0">
                                            <div className="paymentslist-text22">
                                                { item.additionalInfo }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="paymentslist-1-0-1-0-0-0-0-4">
                                        <div className="paymentslist-1-0-1-0-0-0-0-4-0">
                                            <div className="paymentslist-text24">
                                                { item.dateSince }
                                            </div>
                                        </div>
                                        <div className="paymentslist-1-0-1-0-0-0-0-4-1">
                                            <div className="paymentslist-text23">
                                                { item.paymentAmount }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}