// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './paymentlist.css';

function render() {
    return <div className="paymentlist">
        { (this.props.state === "empty") ?
            <div className="paymentlist-empty-4">
                <div className="paymentlist-0-0-0">
                    <div className="paymentlist-rectangle_8">
                        <div className="paymentlist-0-0-0-0-0">
                            <div className="paymentlist-paymentlistheader-2">
                                <div className="paymentlist-0-0-0-0-0-0-0">
                                    <div className="paymentlist-text2">PAYMENTS</div>
                                </div>
                            </div>
                        </div>
                        <div className="paymentlist-0-0-0-0-1">
                            <div className="paymentlist-text_1">
                                {"No payments to show."}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state === "default") ?
            <div className="paymentlist-default-9">
                <div className="paymentlist-1-0-0">
                    <div className="paymentlist-rectangle_7">
                        <div className="paymentlist-1-0-0-0-0">
                            <div className="paymentlist-paymentlistheader-7">
                                <div className="paymentlist-1-0-0-0-0-0-0">
                                    <div className="paymentlist-text20">PAYMENTS</div>
                                </div>
                            </div>
                        </div>
                        <div className="paymentlist-1-0-0-0-1">
                            <div className="paymentlist-paymentlistcontent-6">
                                <div className="paymentlist-1-0-0-0-1-0-0">
                                    <div className="paymentlist-paylistheaders-9">
                                        <div className="paymentlist-1-0-0-0-1-0-0-0-0">
                                            <div className="paymentlist-paylistheader1">Project</div>
                                            <div className="paymentlist-paylistheader2">Details</div>
                                        </div>
                                    </div>
                                </div>
                                <div className="paymentlist-1-0-0-0-1-0-1">
                                    <div className="paymentlist-1-0-0-0-1-0-1-0">
                                        { this.props.list.map((item, i) => {
                                            return <div key={i} className="paymentlist-paymentitem-1">
                                                <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0">
                                                    <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-0">
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-0-0">
                                                            <img src={item.profilePicture} className="paymentlist-paymentprofile-5" /> 
                                                        </div>
                                                    </div>
                                                    <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-1">
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-1-0">
                                                            <div className="paymentlist-text25">
                                                                { item.firstName }
                                                            </div>
                                                        </div>
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-1-1">
                                                            <div className="paymentlist-text26">{ item.lastName }</div>
                                                        </div>
                                                    </div>
                                                    <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-2">
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-2-0">
                                                            <div className="paymentlist-text21">
                                                                { item.projectName }
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-3">
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-3-0">
                                                            <div className="paymentlist-text22">
                                                                { item.additionalInfo }
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-4">
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-4-0">
                                                            <div className="paymentlist-text24">
                                                                { item.dateSince }
                                                            </div>
                                                        </div>
                                                        <div className="paymentlist-1-0-0-0-1-0-1-0-0-0-0-4-1">
                                                            <div className="paymentlist-text23">
                                                                { item.paymentAmount }
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>;
                                        }) }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}