// Generated by https://pagedraw.io/pages/8218
import Pie from '../components/piechart'
import React from 'react';
import './piechart.css';

function render() {
    return <div className="piechart-piechart-2">
        <div className="piechart-0">
            <div className="piechart-rectangle_9">
                <Pie
                  data={ this.props.data }
                  radius={ 100 }
                  hole={ 20 }
                  colors={ this.props.colors }
                  labels={ true }
                  percent={ true }
                  strokeWidth={ 3 }
                  stroke={ '#fff' }/>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}