// Generated by https://pagedraw.io/pages/8218
import Piechart from './piechart';
import Taskcalendar from './taskcalendar';
import Map from './map';
import React from 'react';
import './projectsoverview.css';

function render() {
    return <div className="projectsoverview-projectsoverview-6">
        <div className="projectsoverview-0">
            <div className="projectsoverview-piechart_instance-5">
                <Piechart data={(this.props.statusPie ? this.props.statusPie.data : [])} colors={(this.props.statusPie ? this.props.statusPie.colors : [])} /> 
            </div>
            <div className="projectsoverview-taskcalendar_instance-5">
                <Taskcalendar /> 
            </div>
        </div>
        <div className="projectsoverview-1">
            <div className="projectsoverview-map_instance-1">
                <Map selected={{}} /> 
            </div>
        </div>
        <div className="projectsoverview-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}