// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './taskupdateitem.css';

function render() {
    return <div className="taskupdateitem-taskupdateitem-4">
        <div className="taskupdateitem-0">
            <div className="taskupdateitem-text_9">1mo ago</div>
        </div>
        <div className="taskupdateitem-1">
            <div className="taskupdateitem-1-0">
                <div className="taskupdateitem-1-0-0">
                    <div className="taskupdateitem-oval_3">
                        <div className="taskupdateitem-1-0-0-0-0">
                            <div className="taskupdateitem-text_1">
                                { this.props.updateType }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="taskupdateitem-1-1">
                <div className="taskupdateitem-1-1-0">
                    <div className="taskupdateitem-text_16">
                        { this.props.title }
                    </div>
                </div>
                <div className="taskupdateitem-1-1-1">
                    <div className="taskupdateitem-text_18">
                        { this.props.subtitle }
                    </div>
                </div>
            </div>
            <div className="taskupdateitem-1-2">
                <div className="taskupdateitem-1-2-0">
                    <div className="taskupdateitem-rectangle_6" style={{"background": (this.props.status ? 'rgb(255,193,7)' : '#fff')}}>
                        <div className="taskupdateitem-1-2-0-0-0">
                            <div className="taskupdateitem-text_17">
                                { this.props.status && this.props.status.toUpperCase() }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="taskupdateitem-2">
            <div className="taskupdateitem-line-1" style={{"background": (this.props.isLast ? 'transparent' : '#D8D8D8')}} /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}