// Generated by https://pagedraw.io/pages/8218
import React from 'react';
import './taskcalendar.css';

function render() {
    return <div className="taskcalendar-taskcalendar-4">
        <div className="taskcalendar-0">
            <div className="taskcalendar-rectangle_15">
                <div className="taskcalendar-0-0-0">
                    <div className="taskcalendar-0-0-0-0" /> 
                    <div className="taskcalendar-rectangle_1" /> 
                    <div className="taskcalendar-0-0-0-2" /> 
                </div>
                <div className="taskcalendar-0-0-1" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}