// Generated by https://pagedraw.io/pages/8214
import React from 'react';
import './textinput.css';

function render() {
    return <div className="textinput-textinput-0">
        <div className="textinput-0">
            <input type="text" placeholder={this.props.placeholder} value={this.props.value} name="this.props.name" onChange={this.props.onChange} className="textinput-text_input-4" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}